# note: uncommenting this gives an error: Unrecognized option "json" under "jms_serializer.visitors"
#jms_serializer:
#    visitors:
#        json:
#            options:
#                - JSON_PRETTY_PRINT
#                - JSON_UNESCAPED_SLASHES
#                - JSON_PRESERVE_ZERO_FRACTION
